### ISSUE TITLE
Passing Multiple URLs?

### ISSUE THREAD

**Issue by MrUltimate** [kotartemiy/extract-news-api#1]
Hello! Nice work on the script!

I was wondering if there's a way to handle multiple URLs? Say I want to extract news from 50 different URLs, is there a way I could pass in an object of URLs and receive an aggregate extraction of all articles?

**Comment by kotartemiy** [comment]
Hey, you'd have to do it yourself. 

I may advise using asynchronous calls for a faster response.

**Comment by MrUltimate** [comment]
Thanks @kotartemiy I've gotten as far as getting all the responses the way I want them, but I was wondering if you could help me make them asynchronous? I'm a javascript guy and only know so much python. Here's where I am right now:

https://github.com/MrUltimate/GoodVibesNews/blob/master/src/app.py

I looked up grequests and request-threads but since newspaper3k is the one actually making the calls (and the bulk of the response time), I'm not sure how to restructure it.

Would love this final bit of help! Thanks!
